#!/bin/bash
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root."
    exit 1
fi



MODULE_NAME="rktdev"

MODULE_PATH="$(pwd)/$MODULE_NAME.ko"

CONF_DIR="/etc/modules-load.d"

MODULE_DIR="/lib/modules/$(uname -r)/extra"


if [ ! -f "$MODULE_PATH" ]; then
    echo "Error: '$MODULE_PATH' was not found."
    exit 1
fi


echo "Copying $MODULE_PATH to $MODULE_DIR/$MODULE_NAME.ko"
mkdir -p "$MODULE_DIR"
cp "$MODULE_PATH" "$MODULE_DIR/$MODULE_NAME.ko"


echo "Running depmod..."
depmod -a


mkdir -p "$CONF_DIR"

echo "Configuring the module to load on startup..."
echo "$MODULE_NAME" > "$CONF_DIR/$MODULE_NAME.conf"

echo "$MODULE_NAME will be loaded automatically at startup."